apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: hhkim
spec:
  ports:
  - name: nginx-port
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
  selector:
    app: hello-nginx
